---
abstract: 'add plugins to your Moose classes'
author:
  - 'John SJ Anderson, C<genehack@genehack.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.95'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooseX-Role-Pluggable
no_index:
  directory:
    - inc
    - t
requires:
  Class::MOP: 0
  Moose: 0
  Moose::Role: 0
  Moose::Util::TypeConstraints: 0
  namespace::autoclean: 0
  perl: 5.10.0
resources:
  homepage: http://github.com/genehack/moosex-role-pluggable/tree
  license: http://dev.perl.org/licenses/
  repository: git://github.com/genehack/moosex-role-pluggable.git
version: 0.02
